version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - logs-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "80:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - logs-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.1
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/:/var/dockers-logs/
    ports:
      - 5066:5066
    networks:
      - logs-net

  beats-exporter:
    image: dezmodue/beat-exporter:0.4.0
    container_name: beats-exporter
    ports:
      - "9479:9479"
    depends_on:
      - filebeat
    networks:
      - logs-net
    command:
      - "--beat.uri=http://filebeat:5066"
      - "--web.listen-address=0.0.0.0:9479"
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - logs-net

volumes:
  grafana-storage: {}

networks:
  logs-net:
    driver: bridge